### PR TITLE
basic changes for vgo support

### PR DESCRIPTION
**Pull request by glaslos**
A couple of changes and additions to make vgo work.
I had to put all tests into the wav package to make vgo happy.

### CODE REVIEW

**Comment by mattetti** [comment]
Ohh that's a bummer but thanks so much for adding support for vgo!

**Comment by dmitshur** [comment]
> I had to put all tests into the wav package to make vgo happy.

What was the error you're getting? Which version of Go were you using? I don't think that should be the case.

**Comment by glaslos** [comment]
I was using vgo with 1.10. Issue was that vgo tried to import the `wav_test` package and couldn't find it.

**Comment by dmitshur** [comment]
I see. I suspect it's a bug in 1.10 but has been fixed in Go 1.11.

**Pull request merged**
